### ISSUE TITLE
How to generate the bart_freq_normalized_idx.txt

### ISSUE THREAD

**Issue by Atharva-Phatak** [AshOlogn/Paragraph-level-Simplification-of-Medical-Texts#1]
Hello,

* I wanted to ask how did you generate the files in logr_weights ? Also, can you provide the code to generate these weights ?
* Also where is the code for MLM based metric(SCIBERT) as proposed in paper ?

**Comment by AshOlogn** [comment]
I'll provide the logistic regression and MLM metric code in a couple days!

**Comment by Atharva-Phatak** [comment]
Thanks. That will be helpful

**Comment by Atharva-Phatak** [comment]
@AshOlogn any updates on logistic regression code ??

**Comment by AshOlogn** [comment]
Just pushed it, in the modeling directory
